apply plugin: 'java'
apply plugin: 'idea'

description = 'JMBE Audio Library build script'

java {
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

subprojects {
    apply plugin: 'java'
    version = '1.0.15'

    java {
        sourceCompatibility = JavaVersion.VERSION_25
        targetCompatibility = JavaVersion.VERSION_25
    }
}

idea {
    module {
        downloadJavadoc = true
        downloadSources = true
    }
}
